export interface Armor {
  id: string;
  name: string;
  kind: number;
  price: number;
  zan: number;
  ou: number;
  totsu: number;
  sha: number;
  netsu: number;
  rei: number;
  rai: number;
  jou: number;
  against: string;
  weight: number;
  remarks: string;
  whereToGet: string;
}

export const ARMORS: Armor[] = [
  {
    'id': '0000',
    'name': 'フェイスマスク',
    'kind': 0,
    'price': 1100,
    'zan': 2,
    'ou': 4,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0001',
    'name': 'オープンヘルム',
    'kind': 0,
    'price': 1300,
    'zan': 5,
    'ou': 8,
    'totsu': 2,
    'sha': 2,
    'netsu': 2,
    'rei': 2,
    'rai': 2,
    'jou': 2,
    'against': '',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(40万)'
  },
  {
    'id': '0002',
    'name': 'グリークヘルム',
    'kind': 0,
    'price': 1800,
    'zan': 8,
    'ou': 14,
    'totsu': 3,
    'sha': 3,
    'netsu': 3,
    'rei': 3,
    'rai': 3,
    'jou': 3,
    'against': '',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(80万)'
  },
  {
    'id': '0003',
    'name': 'クロースヘルム',
    'kind': 0,
    'price': 2600,
    'zan': 12,
    'ou': 24,
    'totsu': 5,
    'sha': 5,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '暗',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(120万)'
  },
  {
    'id': '0004',
    'name': 'ライオンヘッド',
    'kind': 0,
    'price': 800,
    'zan': 3,
    'ou': 3,
    'totsu': 3,
    'sha': 3,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '暗',
    'weight': 1,
    'remarks': '',
    'whereToGet': 'ソーモン'
  },
  {
    'id': '0005',
    'name': 'マイティヘルム',
    'kind': 0,
    'price': 2200,
    'zan': 10,
    'ou': 20,
    'totsu': 5,
    'sha': 5,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 1,
    'remarks': '腕力+1',
    'whereToGet': '[敵]トリトーン、ブラックレギオン、ノエル第2形態'
  },
  {
    'id': '0007',
    'name': 'アイアンウィル',
    'kind': 0,
    'price': 2200,
    'zan': 15,
    'ou': 25,
    'totsu': 5,
    'sha': 5,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 30,
    'against': '精',
    'weight': 2,
    'remarks': '',
    'whereToGet': 'モール固定装備'
  },
  {
    'id': '0008',
    'name': 'ヘッドバンド',
    'kind': 0,
    'price': 1000,
    'zan': 1,
    'ou': 0,
    'totsu': 0,
    'sha': 0,
    'netsu': 3,
    'rei': 3,
    'rai': 3,
    'jou': 3,
    'against': '',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0009',
    'name': 'ストローベレー',
    'kind': 0,
    'price': 1000,
    'zan': 5,
    'ou': 5,
    'totsu': 5,
    'sha': 5,
    'netsu': 30,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '開発品(40万)'
  },
  {
    'id': '0010',
    'name': 'とんがり帽子',
    'kind': 0,
    'price': 1000,
    'zan': 3,
    'ou': 3,
    'totsu': 3,
    'sha': 3,
    'netsu': 8,
    'rei': 8,
    'rai': 8,
    'jou': 10,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '[敵]ノービス、シニアー、マスター、ドクター'
  },
  {
    'id': '0012',
    'name': '水鳥の帽子',
    'kind': 0,
    'price': 1000,
    'zan': 2,
    'ou': 2,
    'totsu': 2,
    'sha': 2,
    'netsu': 10,
    'rei': 30,
    'rai': 10,
    'jou': 10,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '赤の迷宮'
  },
  {
    'id': '0013',
    'name': 'マジックハット',
    'kind': 0,
    'price': 1000,
    'zan': 5,
    'ou': 5,
    'totsu': 5,
    'sha': 5,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 10,
    'against': '',
    'weight': 0,
    'remarks': '魔力+2',
    'whereToGet': '[敵]マジシャン'
  },
  {
    'id': '0014',
    'name': 'ラビットイヤー',
    'kind': 0,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 20,
    'rai': 1,
    'jou': 20,
    'against': '暗麻',
    'weight': 0,
    'remarks': '理力+2',
    'whereToGet': '[敵]ゲットー'
  },
  {
    'id': '0015',
    'name': '虹の水環',
    'kind': 0,
    'price': 1000,
    'zan': 3,
    'ou': 3,
    'totsu': 3,
    'sha': 3,
    'netsu': 32,
    'rei': 32,
    'rai': 0,
    'jou': 32,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '雪の遺跡、[敵]ゴールドバウム、水龍'
  },
  {
    'id': '0017',
    'name': '最強の帽子',
    'kind': 0,
    'price': 1000,
    'zan': 13,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '[敵]マッドオーガ、ナックラビー、トリトーン'
  },
  {
    'id': '0019',
    'name': '火神防御輪',
    'kind': 0,
    'price': 10000,
    'zan': 4,
    'ou': 4,
    'totsu': 4,
    'sha': 4,
    'netsu': 128,
    'rei': 0,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': null,
    'remarks': '',
    'whereToGet': '赤の迷宮'
  },
  {
    'id': '0020',
    'name': 'レザーアーマー',
    'kind': 1,
    'price': 1200,
    'zan': 3,
    'ou': 3,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 2,
    'remarks': '',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0021',
    'name': 'リジッドレザー',
    'kind': 1,
    'price': 1800,
    'zan': 7,
    'ou': 7,
    'totsu': 5,
    'sha': 5,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 2,
    'remarks': '',
    'whereToGet': '開発品(40万)'
  },
  {
    'id': '0022',
    'name': 'ブリガンディ',
    'kind': 1,
    'price': 3200,
    'zan': 16,
    'ou': 16,
    'totsu': 10,
    'sha': 10,
    'netsu': 10,
    'rei': 10,
    'rai': 10,
    'jou': 10,
    'against': '',
    'weight': 2,
    'remarks': '',
    'whereToGet': '開発品(80万)'
  },
  {
    'id': '0023',
    'name': 'エルブンスキン',
    'kind': 1,
    'price': 2600,
    'zan': 12,
    'ou': 12,
    'totsu': 6,
    'sha': 6,
    'netsu': 15,
    'rei': 15,
    'rai': 15,
    'jou': 25,
    'against': '麻',
    'weight': 1,
    'remarks': '一度装備すると外せない',
    'whereToGet': 'イーリスの村'
  },
  {
    'id': '0025',
    'name': 'タイガーアーマー',
    'kind': 1,
    'price': 4300,
    'zan': 20,
    'ou': 20,
    'totsu': 10,
    'sha': 10,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 2,
    'remarks': '',
    'whereToGet': '封印の地'
  },
  {
    'id': '0026',
    'name': 'ラビットアーマー',
    'kind': 1,
    'price': 1000,
    'zan': 10,
    'ou': 10,
    'totsu': 10,
    'sha': 10,
    'netsu': 0,
    'rei': 20,
    'rai': 0,
    'jou': 25,
    'against': '毒',
    'weight': 1,
    'remarks': '理力+2',
    'whereToGet': '[敵]ロビンハット'
  },
  {
    'id': '0027',
    'name': 'ワニ革の鎧',
    'kind': 1,
    'price': 800,
    'zan': 8,
    'ou': 8,
    'totsu': 4,
    'sha': 4,
    'netsu': 4,
    'rei': 1,
    'rai': 4,
    'jou': 4,
    'against': '',
    'weight': 2,
    'remarks': '',
    'whereToGet': '[敵]百獣王、人狼、ドラフトレッド、ガリアンブルー、ワニゲータ、リザードマン、リザードレディ、リザードロード'
  },
  {
    'id': '0031',
    'name': '鉄の鎧',
    'kind': 1,
    'price': 1600,
    'zan': 6,
    'ou': 3,
    'totsu': 4,
    'sha': 4,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 5,
    'remarks': '',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0032',
    'name': '鋼鉄の鎧',
    'kind': 1,
    'price': 1900,
    'zan': 8,
    'ou': 5,
    'totsu': 7,
    'sha': 7,
    'netsu': 2,
    'rei': 2,
    'rai': 2,
    'jou': 2,
    'against': '',
    'weight': 5,
    'remarks': '最初から開発済',
    'whereToGet': '開発品(40万)'
  },
  {
    'id': '0033',
    'name': '白銀のチェイル',
    'kind': 1,
    'price': 3000,
    'zan': 15,
    'ou': 10,
    'totsu': 10,
    'sha': 10,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 10,
    'against': '',
    'weight': 4,
    'remarks': '',
    'whereToGet': '開発品(80万)'
  },
  {
    'id': '0034',
    'name': '超銅金の鎧',
    'kind': 1,
    'price': 5700,
    'zan': 25,
    'ou': 15,
    'totsu': 20,
    'sha': 20,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 14,
    'remarks': '',
    'whereToGet': '沈没船、[敵]ドレッドナイト'
  },
  {
    'id': '0036',
    'name': 'ハルモニアの鎧',
    'kind': 1,
    'price': 4300,
    'zan': 20,
    'ou': 15,
    'totsu': 18,
    'sha': 18,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 10,
    'against': '',
    'weight': 4,
    'remarks': '',
    'whereToGet': '開発品(120万)'
  },
  {
    'id': '0037',
    'name': '竜鱗の鎧',
    'kind': 1,
    'price': 10000,
    'zan': 35,
    'ou': 20,
    'totsu': 25,
    'sha': 25,
    'netsu': 30,
    'rei': 30,
    'rai': 30,
    'jou': 5,
    'against': '',
    'weight': 5,
    'remarks': '',
    'whereToGet': '雪の遺跡'
  },
  {
    'id': '0038',
    'name': '黒のガラドリエル',
    'kind': 1,
    'price': 14600,
    'zan': 42,
    'ou': 25,
    'totsu': 30,
    'sha': 30,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '暗',
    'weight': 5,
    'remarks': '',
    'whereToGet': '封印の地'
  },
  {
    'id': '0039',
    'name': '赤熱の鱗',
    'kind': 1,
    'price': 10000,
    'zan': 35,
    'ou': 25,
    'totsu': 25,
    'sha': 25,
    'netsu': 128,
    'rei': 0,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 5,
    'remarks': '',
    'whereToGet': 'サラマンダー固定装備'
  },
  {
    'id': '0040',
    'name': 'セブンスアーマー',
    'kind': 1,
    'price': 20000,
    'zan': 46,
    'ou': 38,
    'totsu': 44,
    'sha': 44,
    'netsu': 12,
    'rei': 12,
    'rai': 12,
    'jou': 5,
    'against': '',
    'weight': 4,
    'remarks': '',
    'whereToGet': '運命の石を武具開発の若者に渡す'
  },
  {
    'id': '0041',
    'name': '魔道師のローブ',
    'kind': 1,
    'price': 1100,
    'zan': 2,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 1,
    'remarks': '魔力+1',
    'whereToGet': '[装]フリーメイジ'
  },
  {
    'id': '0042',
    'name': '玉虫のローブ',
    'kind': 1,
    'price': 1900,
    'zan': 8,
    'ou': 2,
    'totsu': 2,
    'sha': 2,
    'netsu': 10,
    'rei': 0,
    'rai': 10,
    'jou': 10,
    'against': '',
    'weight': 1,
    'remarks': '魔力+1',
    'whereToGet': '白アリの巣、[敵]ノスフェラン、ヒューリオン'
  },
  {
    'id': '0044',
    'name': '星くずのローブ',
    'kind': 1,
    'price': 1300,
    'zan': 4,
    'ou': 2,
    'totsu': 2,
    'sha': 2,
    'netsu': 10,
    'rei': 10,
    'rai': 10,
    'jou': 10,
    'against': '',
    'weight': 1,
    'remarks': '魔力+2',
    'whereToGet': '[敵]ディープワン、ミミック'
  },
  {
    'id': '0045',
    'name': '月影のローブ',
    'kind': 1,
    'price': 1300,
    'zan': 4,
    'ou': 3,
    'totsu': 3,
    'sha': 3,
    'netsu': 15,
    'rei': 15,
    'rai': 15,
    'jou': 15,
    'against': '',
    'weight': 1,
    'remarks': '魔力+3',
    'whereToGet': '[敵]ジョーカー、リリス、人面ザメ、ブラックウィドウ、ラルヴァクィーン'
  },
  {
    'id': '0047',
    'name': '太陽のローブ',
    'kind': 1,
    'price': 2200,
    'zan': 10,
    'ou': 5,
    'totsu': 5,
    'sha': 5,
    'netsu': 25,
    'rei': 25,
    'rai': 25,
    'jou': 25,
    'against': '',
    'weight': 1,
    'remarks': '魔力+2',
    'whereToGet': '[敵]クレイジーサン、メドゥサ、マーリド'
  },
  {
    'id': '0049',
    'name': '宵闇のローブ',
    'kind': 1,
    'price': 2200,
    'zan': 10,
    'ou': 4,
    'totsu': 15,
    'sha': 40,
    'netsu': 30,
    'rei': 30,
    'rai': 30,
    'jou': 30,
    'against': '',
    'weight': 1,
    'remarks': '理力+3',
    'whereToGet': '浮上島、[敵]ヴァンパイア、ミスティック、河馬人間、魔道士'
  },
  {
    'id': '0052',
    'name': 'アバロンの聖衣',
    'kind': 1,
    'price': 4300,
    'zan': 25,
    'ou': 25,
    'totsu': 25,
    'sha': 25,
    'netsu': 25,
    'rei': 25,
    'rai': 25,
    'jou': 25,
    'against': '',
    'weight': 1,
    'remarks': '魔力+2',
    'whereToGet': 'アバロン'
  },
  {
    'id': '0053',
    'name': '識者のローブ',
    'kind': 1,
    'price': 1200,
    'zan': 3,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 10,
    'rei': 10,
    'rai': 10,
    'jou': 10,
    'against': '圧',
    'weight': 1,
    'remarks': '',
    'whereToGet': '宮廷魔術士固定装備'
  },
  {
    'id': '0054',
    'name': 'プロテクトスーツ',
    'kind': 2,
    'price': 2600,
    'zan': 12,
    'ou': 8,
    'totsu': 8,
    'sha': 8,
    'netsu': 6,
    'rei': 6,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': 12,
    'remarks': '',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0055',
    'name': 'ラメラースーツ',
    'kind': 2,
    'price': 3000,
    'zan': 20,
    'ou': 16,
    'totsu': 16,
    'sha': 16,
    'netsu': 10,
    'rei': 10,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 12,
    'remarks': '',
    'whereToGet': '開発品(1段階)'
  },
  {
    'id': '0056',
    'name': 'スウェットスーツ',
    'kind': 2,
    'price': 3200,
    'zan': 15,
    'ou': 15,
    'totsu': 15,
    'sha': 15,
    'netsu': 10,
    'rei': 10,
    'rai': 2,
    'jou': 5,
    'against': '眠',
    'weight': 8,
    'remarks': '',
    'whereToGet': 'サイフリートの砦'
  },
  {
    'id': '0057',
    'name': 'プレートスーツ',
    'kind': 2,
    'price': 4300,
    'zan': 35,
    'ou': 30,
    'totsu': 30,
    'sha': 30,
    'netsu': 20,
    'rei': 20,
    'rai': 3,
    'jou': 3,
    'against': '',
    'weight': 12,
    'remarks': '',
    'whereToGet': '開発品(2段階)'
  },
  {
    'id': '0058',
    'name': 'ヘビースーツ',
    'kind': 2,
    'price': 17300,
    'zan': 55,
    'ou': 45,
    'totsu': 45,
    'sha': 45,
    'netsu': 10,
    'rei': 10,
    'rai': 3,
    'jou': 3,
    'against': '',
    'weight': 18,
    'remarks': '',
    'whereToGet': '青の迷宮'
  },
  {
    'id': '0059',
    'name': 'コンバットスーツ',
    'kind': 2,
    'price': 1000,
    'zan': 25,
    'ou': 20,
    'totsu': 25,
    'sha': 25,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 8,
    'remarks': '',
    'whereToGet': '[敵]マッドオーガ'
  },
  {
    'id': '0060',
    'name': 'ハルモニアスーツ',
    'kind': 2,
    'price': 10000,
    'zan': 45,
    'ou': 35,
    'totsu': 35,
    'sha': 35,
    'netsu': 20,
    'rei': 20,
    'rai': 5,
    'jou': 15,
    'against': '',
    'weight': 10,
    'remarks': '',
    'whereToGet': '開発品(3段階)、[装]最終皇帝'
  },
  {
    'id': '0062',
    'name': 'ヒドラスーツ',
    'kind': 2,
    'price': 22800,
    'zan': 30,
    'ou': 30,
    'totsu': 30,
    'sha': 30,
    'netsu': 30,
    'rei': 30,
    'rai': 5,
    'jou': 10,
    'against': '毒',
    'weight': 16,
    'remarks': '',
    'whereToGet': '[敵]パイロヒドラ、ヴリトラ'
  },
  {
    'id': '0063',
    'name': 'ナックルカバー',
    'kind': 3,
    'price': 1300,
    'zan': 4,
    'ou': 2,
    'totsu': 2,
    'sha': 2,
    'netsu': 0,
    'rei': 0,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0064',
    'name': 'ガントレット',
    'kind': 3,
    'price': 1900,
    'zan': 7,
    'ou': 3,
    'totsu': 3,
    'sha': 3,
    'netsu': 2,
    'rei': 2,
    'rai': 2,
    'jou': 2,
    'against': '',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(40万)'
  },
  {
    'id': '0065',
    'name': 'ヴァンブレイス',
    'kind': 3,
    'price': 3200,
    'zan': 10,
    'ou': 6,
    'totsu': 6,
    'sha': 6,
    'netsu': 3,
    'rei': 3,
    'rai': 3,
    'jou': 3,
    'against': '',
    'weight': 2,
    'remarks': '',
    'whereToGet': '開発品(80万)'
  },
  {
    'id': '0066',
    'name': 'マスタリーグラブ',
    'kind': 3,
    'price': 2200,
    'zan': 12,
    'ou': 8,
    'totsu': 8,
    'sha': 8,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 1,
    'remarks': '器用+2',
    'whereToGet': '開発品(120万)'
  },
  {
    'id': '0067',
    'name': '白手袋',
    'kind': 3,
    'price': 1200,
    'zan': 3,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 0,
    'remarks': '器用+1',
    'whereToGet': '[敵]デュラハン'
  },
  {
    'id': '0068',
    'name': 'ミトン',
    'kind': 3,
    'price': 1200,
    'zan': 2,
    'ou': 2,
    'totsu': 2,
    'sha': 2,
    'netsu': 4,
    'rei': 25,
    'rai': 4,
    'jou': 4,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '[敵]ウオッチマン'
  },
  {
    'id': '0069',
    'name': '怪力手袋',
    'kind': 3,
    'price': 1000,
    'zan': 2,
    'ou': 2,
    'totsu': 2,
    'sha': 2,
    'netsu': 2,
    'rei': 2,
    'rai': 2,
    'jou': 2,
    'against': '',
    'weight': 0,
    'remarks': '腕力+2',
    'whereToGet': '[敵]青鬼、赤鬼、ペグパウラー、バルキリー、シルバービート、ノエル第1形態'
  },
  {
    'id': '0072',
    'name': 'なベつかみ',
    'kind': 3,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 25,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': 'ミラマー'
  },
  {
    'id': '0073',
    'name': '革のすね当て',
    'kind': 4,
    'price': 1300,
    'zan': 4,
    'ou': 2,
    'totsu': 3,
    'sha': 3,
    'netsu': 0,
    'rei': 0,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0074',
    'name': '鋼の具足',
    'kind': 4,
    'price': 1900,
    'zan': 6,
    'ou': 3,
    'totsu': 4,
    'sha': 3,
    'netsu': 2,
    'rei': 2,
    'rai': 2,
    'jou': 2,
    'against': '',
    'weight': 2,
    'remarks': '',
    'whereToGet': '開発品(40万)'
  },
  {
    'id': '0075',
    'name': '白銀の具足',
    'kind': 4,
    'price': 2200,
    'zan': 8,
    'ou': 4,
    'totsu': 6,
    'sha': 6,
    'netsu': 3,
    'rei': 3,
    'rai': 3,
    'jou': 10,
    'against': '',
    'weight': 1,
    'remarks': '',
    'whereToGet': '開発品(80万)'
  },
  {
    'id': '0076',
    'name': 'クイックシルバー',
    'kind': 4,
    'price': 2600,
    'zan': 11,
    'ou': 6,
    'totsu': 10,
    'sha': 10,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 1,
    'remarks': '素早+2',
    'whereToGet': '開発品(120万)'
  },
  {
    'id': '0077',
    'name': 'ラバーソウル',
    'kind': 4,
    'price': 1500,
    'zan': 4,
    'ou': 1,
    'totsu': 4,
    'sha': 4,
    'netsu': 1,
    'rei': 4,
    'rai': 64,
    'jou': 1,
    'against': '',
    'weight': 0,
    'remarks': '素早+1',
    'whereToGet': 'サイフリートの砦、[敵]影、ジン'
  },
  {
    'id': '0079',
    'name': 'マジックブーツ',
    'kind': 4,
    'price': 1600,
    'zan': 6,
    'ou': 6,
    'totsu': 6,
    'sha': 6,
    'netsu': 4,
    'rei': 4,
    'rai': 4,
    'jou': 4,
    'against': '',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': '[敵]ビーストメア、ミスティック'
  },
  {
    'id': '0080',
    'name': 'ヒールのサンダル',
    'kind': 4,
    'price': 1200,
    'zan': 3,
    'ou': 1,
    'totsu': 3,
    'sha': 3,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 0,
    'remarks': '体術「ふみつけ」が使用可能になる',
    'whereToGet': 'シティシーフ(女)固定装備'
  },
  {
    'id': '0082',
    'name': 'フェザーブーツ',
    'kind': 4,
    'price': 1800,
    'zan': 7,
    'ou': 1,
    'totsu': 7,
    'sha': 7,
    'netsu': 3,
    'rei': 3,
    'rai': 3,
    'jou': 3,
    'against': '',
    'weight': 0,
    'remarks': '素早+4',
    'whereToGet': '[敵]ジャン、ノエル第1形態'
  },
  {
    'id': '0083',
    'name': 'ダブレット',
    'kind': 5,
    'price': 1100,
    'zan': 2,
    'ou': 2,
    'totsu': 2,
    'sha': 2,
    'netsu': 2,
    'rei': 2,
    'rai': 2,
    'jou': 2,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '開発品(初期)'
  },
  {
    'id': '0084',
    'name': '武道着',
    'kind': 5,
    'price': 1500,
    'zan': 7,
    'ou': 7,
    'totsu': 7,
    'sha': 7,
    'netsu': 7,
    'rei': 7,
    'rai': 7,
    'jou': 7,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '[装]格闘家、[敵]影、グレート、ノエル第1形態'
  },
  {
    'id': '0086',
    'name': '防護服',
    'kind': 5,
    'price': 1800,
    'zan': 5,
    'ou': 5,
    'totsu': 5,
    'sha': 5,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '開発品(40万)'
  },
  {
    'id': '0087',
    'name': '強化服',
    'kind': 5,
    'price': 1900,
    'zan': 8,
    'ou': 8,
    'totsu': 8,
    'sha': 8,
    'netsu': 8,
    'rei': 8,
    'rai': 8,
    'jou': 8,
    'against': '眠',
    'weight': 0,
    'remarks': '',
    'whereToGet': '開発品(80万)'
  },
  {
    'id': '0088',
    'name': '力帯',
    'kind': 5,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 1,
    'against': '',
    'weight': 0,
    'remarks': '腕力+3',
    'whereToGet': '子供と子ムー、[敵]シルバービート、グレート、ノエル第2形態'
  },
  {
    'id': '0091',
    'name': 'プリマチュチュ',
    'kind': 5,
    'price': 1000,
    'zan': 25,
    'ou': 25,
    'totsu': 25,
    'sha': 25,
    'netsu': 5,
    'rei': 64,
    'rai': 64,
    'jou': 5,
    'against': '毒精暗眠麻',
    'weight': 0,
    'remarks': '全身を覆う服なので盾、アクセ以外装備不可',
    'whereToGet': 'コッペリア固定装備'
  },
  {
    'id': '0093',
    'name': '断熱服',
    'kind': 5,
    'price': 1000,
    'zan': 5,
    'ou': 5,
    'totsu': 5,
    'sha': 5,
    'netsu': 32,
    'rei': 32,
    'rai': 5,
    'jou': 5,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '地上戦艦、[敵]ヒューリオン、ボクオーン'
  },
  {
    'id': '0095',
    'name': '風花のショール',
    'kind': 5,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 128,
    'rai': 0,
    'jou': 30,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': 'イーリス固定装備'
  },
  {
    'id': '0096',
    'name': 'シルバーリング',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 4,
    'rei': 4,
    'rai': 4,
    'jou': 4,
    'against': '',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': '[装]レオン、[敵]ニクサー'
  },
  {
    'id': '0098',
    'name': 'キャッツアイ',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 15,
    'against': '暗',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': '[敵]魔道士、ロックブーケ第1形態'
  },
  {
    'id': '0099',
    'name': 'スターストーン',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 32,
    'rei': 1,
    'rai': 1,
    'jou': 10,
    'against': '',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': '[敵]スカルデーモン、ゼノ、カルト、ベインパープル、ワグナス'
  },
  {
    'id': '0101',
    'name': '魔石の指輪',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 16,
    'rei': 16,
    'rai': 16,
    'jou': 32,
    'against': '精',
    'weight': 0,
    'remarks': '魔力+1、一度装備すると外せない、宿泊時装備者以外LP-1',
    'whereToGet': 'モールの穴で魔石のかけらを加工'
  },
  {
    'id': '0104',
    'name': '精霊の指輪',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 10,
    'rei': 10,
    'rai': 10,
    'jou': 10,
    'against': '',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': '[敵]トウテツ、ラルヴァクィーン'
  },
  {
    'id': '0105',
    'name': 'キャンディリング',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 20,
    'rai': 20,
    'jou': 20,
    'against': '圧',
    'weight': 0,
    'remarks': '理力+3',
    'whereToGet': '[敵]ゼラチナスマター'
  },
  {
    'id': '0106',
    'name': 'ニーベルの指輪',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 10,
    'rai': 1,
    'jou': 10,
    'against': '',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': 'モンスターの巣'
  },
  {
    'id': '0107',
    'name': 'メロウリング',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 32,
    'rei': 128,
    'rai': 0,
    'jou': 30,
    'against': '',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': 'ネレイド固定装備'
  },
  {
    'id': '0108',
    'name': 'クリスナイフ',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 5,
    'rei': 5,
    'rai': 5,
    'jou': 20,
    'against': '',
    'weight': 0,
    'remarks': '',
    'whereToGet': '封印の地、[敵]スカルロード、トウテツ、水龍'
  },
  {
    'id': '0110',
    'name': 'ラビットフット',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 20,
    'rai': 0,
    'jou': 20,
    'against': '眠',
    'weight': 0,
    'remarks': '理力+1',
    'whereToGet': '[敵]ウオッチマン'
  },
  {
    'id': '0111',
    'name': 'ソーモンの指輪',
    'kind': 6,
    'price': 1000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 1,
    'rei': 1,
    'rai': 1,
    'jou': 5,
    'against': '精',
    'weight': 0,
    'remarks': '魔力+1',
    'whereToGet': 'ソーモン'
  },
  {
    'id': '0112',
    'name': 'パワーリング',
    'kind': 6,
    'price': 10000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 8,
    'rei': 0,
    'rai': 8,
    'jou': 0,
    'against': '',
    'weight': 0,
    'remarks': '腕力+4',
    'whereToGet': '緑の迷宮'
  },
  {
    'id': '0113',
    'name': 'シーフリング',
    'kind': 6,
    'price': 10000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 8,
    'rai': 8,
    'jou': 0,
    'against': '',
    'weight': 0,
    'remarks': '器用さ+4',
    'whereToGet': '赤の迷宮'
  },
  {
    'id': '0114',
    'name': 'マジックリング',
    'kind': 6,
    'price': 10000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 8,
    'rai': 0,
    'jou': 8,
    'against': '',
    'weight': 0,
    'remarks': '魔力+4',
    'whereToGet': '黒の迷宮'
  },
  {
    'id': '0115',
    'name': 'クイックリング',
    'kind': 6,
    'price': 10000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 8,
    'rei': 0,
    'rai': 0,
    'jou': 8,
    'against': '',
    'weight': 0,
    'remarks': '素早さ+4',
    'whereToGet': '青の迷宮'
  },
  {
    'id': '0116',
    'name': 'スキルリング',
    'kind': 6,
    'price': 5000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 0,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': 0,
    'remarks': '装備者の取得技術点UP',
    'whereToGet': '青の迷宮'
  },
  {
    'id': '0117',
    'name': 'ドロップリング',
    'kind': 6,
    'price': 5000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 0,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': 0,
    'remarks': 'ドロップ率アップ',
    'whereToGet': '青の迷宮'
  },
  {
    'id': '0118',
    'name': '火の指輪',
    'kind': 6,
    'price': 5000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 64,
    'rei': 0,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': 0,
    'remarks': '火地相でHP自動回復',
    'whereToGet': '赤の迷宮'
  },
  {
    'id': '0119',
    'name': '水の指輪',
    'kind': 6,
    'price': 5000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 64,
    'rai': 0,
    'jou': 0,
    'against': '',
    'weight': 0,
    'remarks': '水地相でHP自動回復',
    'whereToGet': '青の迷宮'
  },
  {
    'id': '0120',
    'name': '風の指輪',
    'kind': 6,
    'price': 5000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 0,
    'rai': 64,
    'jou': 0,
    'against': '',
    'weight': 0,
    'remarks': '風地相でHP自動回復',
    'whereToGet': '緑の迷宮'
  },
  {
    'id': '0121',
    'name': '地の指輪',
    'kind': 6,
    'price': 5000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 0,
    'rai': 0,
    'jou': 64,
    'against': '',
    'weight': 0,
    'remarks': '地地相でHP自動回復',
    'whereToGet': '黒の迷宮'
  },
  {
    'id': '0122',
    'name': 'インタリオリング',
    'kind': 6,
    'price': 10000,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 8,
    'rei': 8,
    'rai': 8,
    'jou': 8,
    'against': '麻眠暗精毒',
    'weight': 0,
    'remarks': '',
    'whereToGet': 'ヴィクトールの亡霊'
  },
  {
    'id': '0124',
    'name': 'ダッシュリング',
    'kind': 6,
    'price': null,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 0,
    'rei': 0,
    'rai': 0,
    'jou': 32,
    'against': '',
    'weight': 0,
    'remarks': 'ダッシュ時の視界拡大',
    'whereToGet': '忍者固定装備'
  },
  {
    'id': '0125',
    'name': '百鬼の指輪',
    'kind': 6,
    'price': null,
    'zan': 1,
    'ou': 1,
    'totsu': 1,
    'sha': 1,
    'netsu': 16,
    'rei': 16,
    'rai': 16,
    'jou': 16,
    'against': '精',
    'weight': 0,
    'remarks': '',
    'whereToGet': '陰陽師固定装備'
  }
];
